apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: another-secret
